In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

pd.set_option('display.float_format',lambda x : '%.2f' % x)
import warnings
warnings.filterwarnings('ignore')

In [3]:
dt=pd.read_csv('./电子产品销售分析.csv',index_col=0,dtype={'category_id':'int64','user_id':'int64'})

In [4]:
dt.head()

,event_time,order_id,product_id,category_id,category_code,brand,price,user_id,age,sex,local
0,2020-04-24 11:50:39 UTC,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南
1,2020-04-24 11:50:39 UTC,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南
2,2020-04-24 14:37:43 UTC,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京
3,2020-04-24 14:37:43 UTC,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京
4,2020-04-24 19:16:21 UTC,2294584263154074236,2273948316817424439,2268105471367840000,NaN,karcher,217.57,1515915625443148032,32.00,女,广东

In [5]:
dt['date']=dt.event_time.apply(lambda x: x.split(' ')[0])

In [6]:
dt.head()

,event_time,order_id,product_id,category_id,category_code,brand,price,user_id,age,sex,local,date
0,2020-04-24 11:50:39 UTC,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南,2020-04-24
1,2020-04-24 11:50:39 UTC,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南,2020-04-24
2,2020-04-24 14:37:43 UTC,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京,2020-04-24
3,2020-04-24 14:37:43 UTC,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京,2020-04-24
4,2020-04-24 19:16:21 UTC,2294584263154074236,2273948316817424439,2268105471367840000,NaN,karcher,217.57,1515915625443148032,32.00,女,广东,2020-04-24

In [7]:
dt.date=pd.to_datetime(dt.date)

In [8]:
dt.head()

,event_time,order_id,product_id,category_id,category_code,brand,price,user_id,age,sex,local,date
0,2020-04-24 11:50:39 UTC,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南,2020-04-24
1,2020-04-24 11:50:39 UTC,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南,2020-04-24
2,2020-04-24 14:37:43 UTC,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京,2020-04-24
3,2020-04-24 14:37:43 UTC,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京,2020-04-24
4,2020-04-24 19:16:21 UTC,2294584263154074236,2273948316817424439,2268105471367840000,NaN,karcher,217.57,1515915625443148032,32.00,女,广东,2020-04-24

In [9]:
dt['month']=dt.date.dt.month

In [10]:
dt['hour']=dt.event_time.apply(lambda x:x.split(' ')[1].split(':')[0])

In [12]:
dt['weekday']=dt.date.apply(lambda x:x.strftime('%w'))

In [13]:
del dt['event_time']

In [14]:
dt.head()

,order_id,product_id,category_id,category_code,brand,price,user_id,age,sex,local,date,month,hour,weekday
0,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南,2020-04-24,4,11,5
1,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南,2020-04-24,4,11,5
2,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京,2020-04-24,4,14,5
3,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京,2020-04-24,4,14,5
4,2294584263154074236,2273948316817424439,2268105471367840000,NaN,karcher,217.57,1515915625443148032,32.00,女,广东,2020-04-24,4,19,5

In [15]:
dt.shape

(564169, 14)

In [16]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 564169 entries, 0 to 2633520
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_id       564169 non-null  int64
 1   product_id     564169 non-null  int64
 2   category_id    564169 non-null  int64
 3   category_code  434799 non-null  object
 4   brand          536945 non-null  object
 5   price          564169 non-null  float64
 6   user_id        564169 non-null  int64
 7   age            564169 non-null  float64
 8   sex            564169 non-null  object
 9   local          564169 non-null  object
 10  date           564169 non-null  datetime64[ns]
 11  month          564169 non-null  int64
 12  hour           564169 non-null  object
 13  weekday        564169 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(5), object(6)
memory usage: 64.6+ MB

In [17]:
dt.category_code=dt.category_code.fillna('R')

In [18]:
dt=dt[dt.brand.notnull()]

In [19]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 536945 entries, 0 to 2633520
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_id       536945 non-null  int64
 1   product_id     536945 non-null  int64
 2   category_id    536945 non-null  int64
 3   category_code  536945 non-null  object
 4   brand          536945 non-null  object
 5   price          536945 non-null  float64
 6   user_id        536945 non-null  int64
 7   age            536945 non-null  float64
 8   sex            536945 non-null  object
 9   local          536945 non-null  object
 10  date           536945 non-null  datetime64[ns]
 11  month          536945 non-null  int64
 12  hour           536945 non-null  object
 13  weekday        536945 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(5), object(6)
memory usage: 61.4+ MB

In [20]:
dt.duplicated().sum()

634

In [21]:
dt.duplicated()

0          False
1           True
2          False
3           True
4          False
           ...
2633516    False
2633517    False
2633518    False
2633519    False
2633520    False
Length: 536945, dtype: bool

In [23]:
df=dt.groupby(['order_id','product-id']).agg(buy_cnt=('user_id','count'))

In [24]:
df

                                         buy_cnt
order_id            product_id
2294359932054536986 1515966223509089906        2
2294444024058086220 2273948319057183658        2
2294584263154074236 2273948316817424439        1
2295716521449619559 1515966223509261697        1
2295740594749702229 1515966223509104892        4
...                                          ...
2388440981134693942 1515966223526602848        1
2388440981134693943 1515966223509089282        1
2388440981134693944 1515966223509089917        1
                    1515966223509127566        1
                    2273948184839454837        1

[536311 rows x 1 columns]

In [27]:
dt=pd.merge(dt,df,on=['order_id','product_id'],how='inner')
dt=dt.drop_duplicates().reset_index(drop=True)

In [28]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536311 entries, 0 to 536310
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_id       536311 non-null  int64
 1   product_id     536311 non-null  int64
 2   category_id    536311 non-null  int64
 3   category_code  536311 non-null  object
 4   brand          536311 non-null  object
 5   price          536311 non-null  float64
 6   user_id        536311 non-null  int64
 7   age            536311 non-null  float64
 8   sex            536311 non-null  object
 9   local          536311 non-null  object
 10  date           536311 non-null  datetime64[ns]
 11  month          536311 non-null  int64
 12  hour           536311 non-null  object
 13  weekday        536311 non-null  object
 14  buy_cnt_x      536311 non-null  int64
 15  buy_cnt_y      536311 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(7), object(6)
memory usage: 65.5+ MB

In [38]:
dt['amount']=dt.price*dt.buy_cnt_x

In [41]:

del dt['buy_cnt_y']

In [42]:
dt

,order_id,product_id,category_id,category_code,brand,price,user_id,age,sex,local,date,month,hour,weekday,buy_cnt_x,amount
0,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南,2020-04-24,4,11,5,2,324.02
1,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京,2020-04-24,4,14,5,2,155.04
2,2294584263154074236,2273948316817424439,2268105471367840000,R,karcher,217.57,1515915625443148032,32.00,女,广东,2020-04-24,4,19,5,1,217.57
3,2295716521449619559,1515966223509261697,2268105442636858112,furniture.kitchen.table,maestro,39.33,1515915625450382848,20.00,男,重庆,2020-04-26,4,08,0,1,39.33
4,2295740594749702229,1515966223509104892,2268105428166508800,electronics.smartphone,apple,1387.01,1515915625448766464,21.00,男,北京,2020-04-26,4,09,0,4,5548.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536306,2388440981134693942,1515966223526602848,2268105428166508800,electronics.smartphone,oppo,138.87,1515915625514888704,21.00,男,上海,2020-11-21,11,10,6,1,138.87
536307,2388440981134693943,1515966223509089282,2268105428166508800,electronics.smartphone,apple,418.96,1515915625514891264,21.00,女,北京,2020-11-21,11,10,6,1,418.96
536308,2388440981134693944,1515966223509089917,2268105402447036928,appliances.personal.scales,vitek,12.48,1515915625514834176,19.00,女,上海,2020-11-21,11,10,6,1,12.48
536309,2388440981134693944,2273948184839454837,2268105440371933952,R,moulinex,41.64,1515915625514834176,19.00,女,上海,2020-11-21,11,10,6,1,41.64
536310,2388440981134693944,1515966223509127566,2268105441101742848,appliances.kitchen.blender,redmond,53.22,1515915625514834176,19.00,女,上海,2020-11-21,11,10,6,1,53.22

In [43]:
dt.rename(columns={'buy_cnt_x':'buy_cnt'},inplace=True)

In [44]:
dt

,order_id,product_id,category_id,category_code,brand,price,user_id,age,sex,local,date,month,hour,weekday,buy_cnt,amount
0,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南,2020-04-24,4,11,5,2,324.02
1,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京,2020-04-24,4,14,5,2,155.04
2,2294584263154074236,2273948316817424439,2268105471367840000,R,karcher,217.57,1515915625443148032,32.00,女,广东,2020-04-24,4,19,5,1,217.57
3,2295716521449619559,1515966223509261697,2268105442636858112,furniture.kitchen.table,maestro,39.33,1515915625450382848,20.00,男,重庆,2020-04-26,4,08,0,1,39.33
4,2295740594749702229,1515966223509104892,2268105428166508800,electronics.smartphone,apple,1387.01,1515915625448766464,21.00,男,北京,2020-04-26,4,09,0,4,5548.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536306,2388440981134693942,1515966223526602848,2268105428166508800,electronics.smartphone,oppo,138.87,1515915625514888704,21.00,男,上海,2020-11-21,11,10,6,1,138.87
536307,2388440981134693943,1515966223509089282,2268105428166508800,electronics.smartphone,apple,418.96,1515915625514891264,21.00,女,北京,2020-11-21,11,10,6,1,418.96
536308,2388440981134693944,1515966223509089917,2268105402447036928,appliances.personal.scales,vitek,12.48,1515915625514834176,19.00,女,上海,2020-11-21,11,10,6,1,12.48
536309,2388440981134693944,2273948184839454837,2268105440371933952,R,moulinex,41.64,1515915625514834176,19.00,女,上海,2020-11-21,11,10,6,1,41.64
536310,2388440981134693944,1515966223509127566,2268105441101742848,appliances.kitchen.blender,redmond,53.22,1515915625514834176,19.00,女,上海,2020-11-21,11,10,6,1,53.22

In [45]:
dt.order_id=dt.order_id.astype('object')
dt.product_id=dt.product_id.astype('object')
dt.category_id=dt.category_id.astype('object')
dt.user_id=dt.user_id.astype('object')

In [46]:
dt.hour=dt.hour.astype('int')
dt.weekday=dt.weekday.astype('int')

In [47]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536311 entries, 0 to 536310
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_id       536311 non-null  object
 1   product_id     536311 non-null  object
 2   category_id    536311 non-null  object
 3   category_code  536311 non-null  object
 4   brand          536311 non-null  object
 5   price          536311 non-null  float64
 6   user_id        536311 non-null  object
 7   age            536311 non-null  float64
 8   sex            536311 non-null  object
 9   local          536311 non-null  object
 10  date           536311 non-null  datetime64[ns]
 11  month          536311 non-null  int64
 12  hour           536311 non-null  int32
 13  weekday        536311 non-null  int32
 14  buy_cnt        536311 non-null  int64
 15  amount         536311 non-null  float64
dtypes: datetime64[ns](1), float64(3), int32(2), int64(2), object(8)
memory usage: 61.4+ MB

In [48]:
dt.describe(percentiles=[0.01,0.25,0.75,0.99])

          price       age     month      hour   weekday   buy_cnt    amount
count 536311.00 536311.00 536311.00 536311.00 536311.00 536311.00 536311.00
mean     214.54     33.18      7.72      9.52      3.03      1.00    214.73
std      305.98     10.12      2.56      4.21      2.04      0.04    306.48
min        0.00     16.00      1.00      0.00      0.00      1.00      0.00
1%         1.13     16.00      1.00      1.00      0.00      1.00      1.13
25%       24.51     24.00      6.00      6.00      1.00      1.00     24.98
50%       99.51     33.00      8.00      9.00      3.00      1.00     99.51
75%      289.33     42.00     10.00     12.00      5.00      1.00    289.33
99%     1387.01     50.00     11.00     22.00      6.00      1.00   1387.01
max    11574.05     50.00     11.00     23.00      6.00      4.00  11574.05

In [49]:
dt.describe(include='all')

,order_id,product_id,category_id,category_code,brand,price,user_id,age,sex,local,date,month,hour,weekday,buy_cnt,amount
count,536311.00,536311.00,536311.00,536311,536311,536311.00,536311.00,536311.00,536311,536311,536311,536311.00,536311.00,536311.00,536311.00,536311.00
unique,389511.00,19078.00,786.00,124,868,NaN,92769.00,NaN,2,11,323,NaN,NaN,NaN,NaN,NaN
top,2388440981134689792.00,1515966223517847040.00,2268105428166508800.00,R,samsung,NaN,1515915625512422912.00,NaN,男,广东,2020-10-22 00:00:00,NaN,NaN,NaN,NaN,NaN
freq,47.00,2755.00,101081.00,116093,96123,NaN,1026.00,NaN,270454,117097,8310,NaN,NaN,NaN,NaN,NaN
first,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN
last,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-11-21 00:00:00,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,214.54,NaN,33.18,NaN,NaN,NaN,7.72,9.52,3.03,1.00,214.73
std,NaN,NaN,NaN,NaN,NaN,305.98,NaN,10.12,NaN,NaN,NaN,2.56,4.21,2.04,0.04,306.48
min,NaN,NaN,NaN,NaN,NaN,0.00,NaN,16.00,NaN,NaN,NaN,1.00,0.00,0.00,1.00,0.00
25%,NaN,NaN,NaN,NaN,NaN,24.51,NaN,24.00,NaN,NaN,NaN,6.00,6.00,1.00,1.00,24.98
50%,NaN,NaN,NaN,NaN,NaN,99.51,NaN,33.00,NaN,NaN,NaN,8.00,9.00,3.00,1.00,99.51
75%,NaN,NaN,NaN,NaN,NaN,289.33,NaN,42.00,NaN,NaN,NaN,10.00,12.00,5.00,1.00,289.33
max,NaN,NaN,NaN,NaN,NaN,11574.05,NaN,50.00,NaN,NaN,NaN,11.00,23.00,6.00,4.00,11574.05

In [50]:
dt=dt[dt.date>'1970-01-01']

In [51]:
dt.date.min()

Timestamp('2020-01-05 00:00:00')

In [52]:
dt.head()

,order_id,product_id,category_id,category_code,brand,price,user_id,age,sex,local,date,month,hour,weekday,buy_cnt,amount
0,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南,2020-04-24,4,11,5,2,324.02
1,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京,2020-04-24,4,14,5,2,155.04
2,2294584263154074236,2273948316817424439,2268105471367840000,R,karcher,217.57,1515915625443148032,32.00,女,广东,2020-04-24,4,19,5,1,217.57
3,2295716521449619559,1515966223509261697,2268105442636858112,furniture.kitchen.table,maestro,39.33,1515915625450382848,20.00,男,重庆,2020-04-26,4,8,0,1,39.33
4,2295740594749702229,1515966223509104892,2268105428166508800,electronics.smartphone,apple,1387.01,1515915625448766464,21.00,男,北京,2020-04-26,4,9,0,4,5548.04

In [53]:
dt.shape

(535065, 16)

In [54]:
dt.reset_index(drop=True,inplace=True)

In [55]:
dt.head()

,order_id,product_id,category_id,category_code,brand,price,user_id,age,sex,local,date,month,hour,weekday,buy_cnt,amount
0,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南,2020-04-24,4,11,5,2,324.02
1,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京,2020-04-24,4,14,5,2,155.04
2,2294584263154074236,2273948316817424439,2268105471367840000,R,karcher,217.57,1515915625443148032,32.00,女,广东,2020-04-24,4,19,5,1,217.57
3,2295716521449619559,1515966223509261697,2268105442636858112,furniture.kitchen.table,maestro,39.33,1515915625450382848,20.00,男,重庆,2020-04-26,4,8,0,1,39.33
4,2295740594749702229,1515966223509104892,2268105428166508800,electronics.smartphone,apple,1387.01,1515915625448766464,21.00,男,北京,2020-04-26,4,9,0,4,5548.04

In [56]:
dt.amount.sum()

114986635.88000001

In [57]:
round(dt.amount.sum(),0)

114986636.0

In [58]:
GMV_month=dt.groupby('month').agg(GMV=('amount','sum'))

In [59]:
GMV_month

              GMV
month
1      1729464.93
2      2216672.31
3      2841015.58
4      1674450.68
5      7657332.51
6      7489312.32
7     16048807.99
8     27380899.66
9     16797132.61
10    19376572.75
11    11774974.54

In [98]:
from pyecharts.charts import Line,Bar,Pie

In [62]:
line=(Line()
     .add_xaxis(GMV_month.index.tolist())
     .add_yaxis('',GMV_month.values.tolist())
     .set_global_opts(title_opts=opts.TitleOpts(title='每月GMV')))
line.render_notebook()

NameError: name 'opts' is not defined

In [63]:
from pyecharts import options as opts

In [65]:
s0=dt.groupby('date').agg(销量=('buy_cnt','sum'),销售额=('amount','sum')).reset_index()

In [66]:
s0

          date    销量        销售额
0   2020-01-05   580   77216.52
1   2020-01-06   565   61146.03
2   2020-01-07   706   82381.21
3   2020-01-08   446   56344.74
4   2020-01-09   449   58278.71
..         ...   ...        ...
317 2020-11-17   880  274274.37
318 2020-11-18  7809 1148309.01
319 2020-11-19  7628 1124239.09
320 2020-11-20   685  267638.53
321 2020-11-21   291  117472.30

[322 rows x 3 columns]

In [67]:
s0['累计销量']=s0.销量.cumsum()

In [68]:
s0

          date    销量        销售额    累计销量
0   2020-01-05   580   77216.52     580
1   2020-01-06   565   61146.03    1145
2   2020-01-07   706   82381.21    1851
3   2020-01-08   446   56344.74    2297
4   2020-01-09   449   58278.71    2746
..         ...   ...        ...     ...
317 2020-11-17   880  274274.37  519286
318 2020-11-18  7809 1148309.01  527095
319 2020-11-19  7628 1124239.09  534723
320 2020-11-20   685  267638.53  535408
321 2020-11-21   291  117472.30  535699

[322 rows x 4 columns]

In [69]:
s0['累计销售额']=s0.销售额.cumsum()
s0['销量增长']=s0.销量.diff()
s0['销量增长率']=s0.销量.pct_change()*100
s0['销售额增长']=s0.销售额.diff()
s0['销售额增长率']=s0.销售额.pct_change()*100

In [70]:
s0

,date,销量,销售额,累计销量,累计销售额,销量增长,销量增长率,销售额增长,销售额增长率
0,2020-01-05,580,77216.52,580,77216.52,NaN,NaN,NaN,NaN
1,2020-01-06,565,61146.03,1145,138362.55,-15.00,-2.59,-16070.49,-20.81
2,2020-01-07,706,82381.21,1851,220743.76,141.00,24.96,21235.18,34.73
3,2020-01-08,446,56344.74,2297,277088.50,-260.00,-36.83,-26036.47,-31.60
4,2020-01-09,449,58278.71,2746,335367.21,3.00,0.67,1933.97,3.43
...,...,...,...,...,...,...,...,...,...
317,2020-11-17,880,274274.37,519286,112328976.95,-1076.00,-55.01,-170670.25,-38.36
318,2020-11-18,7809,1148309.01,527095,113477285.96,6929.00,787.39,874034.64,318.67
319,2020-11-19,7628,1124239.09,534723,114601525.05,-181.00,-2.32,-24069.92,-2.10
320,2020-11-20,685,267638.53,535408,114869163.58,-6943.00,-91.02,-856600.56,-76.19
321,2020-11-21,291,117472.30,535699,114986635.88,-394.00,-57.52,-150166.23,-56.11

In [74]:
p0=(Line()
   .add_xaxis(s0.date.dt.strftime('%m-%d').tolist())
   .add_yaxis('累计销售额(万)',[round(x/10000) for x in s0.累计销售额.tolist()],label_opts=opts.LabelOpts(is_show=False,rotate=-45))
   .add_yaxis('累计销量(件)',s0.累计销量.to_list(),label_opts=opts.LabelOpts(is_show=False,rotate=-45),yaxis_index=1)
   .extend_axis(yaxis=opts.AxisOpts(axislabel_opts=opts.LabelOpts(formatter='{value}件',interval=5000)))
   .set_global_opts(xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=-30)),
                   tooltip_opts=opts.TooltipOpts(trigger='axis'),
                   title_opts=opts.TitleOpts(title='销售额/销量 累计增长',subtitle='|'),
                   yaxis_opts=opts.AxisOpts(name='累计销售额(单位:万)',axislabel_opts=opts.LabelOpts(formatter='{value}万')),
                   datazoom_opts=opts.DataZoomOpts(is_show=True)))
p0.render_notebook()

In [75]:
GMV_month['环比增长']=GMV_month.GMV.diff()
GMV_month['环比增长率']=GMV_month.GMV.pct_change()*100
GMV_month

              GMV         环比增长  环比增长率
month
1      1729464.93          NaN    NaN
2      2216672.31    487207.38  28.17
3      2841015.58    624343.27  28.17
4      1674450.68  -1166564.90 -41.06
5      7657332.51   5982881.83 357.30
6      7489312.32   -168020.19  -2.19
7     16048807.99   8559495.67 114.29
8     27380899.66  11332091.67  70.61
9     16797132.61 -10583767.05 -38.65
10    19376572.75   2579440.14  15.36
11    11774974.54  -7601598.21 -39.23

In [83]:
p1=(Bar()
   .add_xaxis([str(x)+'月' for x in GMV_month.index.tolist()])
   .add_yaxis('月-GMV(万)',[round(x/10000,2)for x in GMV_month.GMV.tolist()])
   .add_yaxis('环比增长(万)',[round(x/10000,2)for x in GMV_month.环比增长.tolist()])
   .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
   .set_global_opts(tooltip_opts=opts.TooltipOpts(trigger='axis'),
                   toolbox_opts=opts.ToolboxOpts(is_show=True),
                   title_opts=opts.TitleOpts(title='每月GMV/环比增长',subtitle='。。。'),
                   yaxis_opts=opts.AxisOpts(name='金额(万)',axislabel_opts=opts.LabelOpts(formatter='{value}万')))
   .extend_axis(yaxis=opts.AxisOpts(name='百分比',axislabel_opts=opts.LabelOpts(formatter='{value}%'))))
line=(Line()
     .add_xaxis([str(x)+'月' for x in GMV_month.index.tolist()])
     .add_yaxis('环比增长率(%)',[round(x,2)for x in GMV_month.环比增长率.tolist()],yaxis_index=1))

p1.overlap(line)
p1.render_notebook()

In [84]:
s2=dt.groupby('month').agg(销量=('buy_cnt','sum'))
s2

          销量
month
1      13449
2      16948
3      17667
4      11348
5      38666
6      39147
7      73404
8      96084
9      67309
10     98191
11     63486

In [85]:
s2['环比增长']=s2.销量.diff()
s2['环比增长率']=s2.销量.pct_change()*100
s2

          销量      环比增长  环比增长率
month
1      13449       NaN    NaN
2      16948   3499.00  26.02
3      17667    719.00   4.24
4      11348  -6319.00 -35.77
5      38666  27318.00 240.73
6      39147    481.00   1.24
7      73404  34257.00  87.51
8      96084  22680.00  30.90
9      67309 -28775.00 -29.95
10     98191  30882.00  45.88
11     63486 -34705.00 -35.34

In [89]:
p2=(Bar()
   .add_xaxis([str(x)+'月' for x in s2.index.tolist()])
   .add_yaxis('月-销量(件)',[x for x in s2.销量.tolist()])
   .add_yaxis('环比增长(件)',[x for x in s2.环比增长.tolist()])
   .extend_axis(yaxis=opts.AxisOpts(name='百分比',axislabel_opts=opts.LabelOpts(formatter='{value}%')))
   .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
   .set_global_opts(tooltip_opts=opts.TooltipOpts(trigger='axis'),
                   title_opts=opts.TitleOpts(title='每月销量/环比增长',subtitle='。。。'),
                   yaxis_opts=opts.AxisOpts(name='销量(单位:件)',axislabel_opts=opts.LabelOpts(formatter='{value}件'))))

line=(Line()
     .add_xaxis([str(x)+'月' for x in s2.index.tolist()])
     .add_yaxis('环比增长率(%)',[round(x,2) for x in s2.环比增长率.tolist()],yaxis_index=1))

p2.overlap(line)

p2.render_notebook()

In [90]:
s3=dt.groupby('product_id').agg(销量=('buy_cnt','sum'),销售额=('amount','sum'))
s3.sort_values(by='销量',ascending=False,inplace=True)
s3=s3[:10]
s3

                       销量        销售额
product_id
1515966223517846928  2759  478934.81
1515966223509106786  2597  360645.39
1515966223509088532  2550  767295.00
1515966223509088613  2549  519180.32
1515966223509088567  2497 2138006.31
1515966223510174551  2370  493694.70
1515966223509088521  2156  249492.32
1515966223509104145  2037  471015.51
1515966223509088639  1904  661068.80
1515966223509117074  1797   54035.79

In [91]:
s3['销量占比%']=s3.销量/(s3.销量.sum())*100
s3['销售额占比%']=s3.销售额/(s3.销售额.sum())*100
s3

                       销量        销售额  销量占比%  销售额占比%
product_id
1515966223517846928  2759  478934.81  11.88    7.73
1515966223509106786  2597  360645.39  11.19    5.82
1515966223509088532  2550  767295.00  10.98   12.39
1515966223509088613  2549  519180.32  10.98    8.38
1515966223509088567  2497 2138006.31  10.76   34.52
1515966223510174551  2370  493694.70  10.21    7.97
1515966223509088521  2156  249492.32   9.29    4.03
1515966223509104145  2037  471015.51   8.77    7.61
1515966223509088639  1904  661068.80   8.20   10.67
1515966223509117074  1797   54035.79   7.74    0.87

In [92]:
s4=dt.groupby('category_code').agg(销量=('buy_cnt','sum'),销售额=('amount','sum'))
s4.sort_values(by='销量',ascending=False,inplace=True)
s4=s4[:10]
s4['销量占比%']=s4.销量/(s4.销量.sum())*100
s4['销售额占比%']=s4.销售额/(s4.销售额.sum())*100
s4

                                      销量         销售额  销量占比%  销售额占比%
category_code
R                                 115809  8216327.01  32.78    9.00
electronics.smartphone            102169 41214019.09  28.92   45.17
computers.notebook                 25860 14785855.65   7.32   16.20
appliances.kitchen.refrigerators   20020  8598364.87   5.67    9.42
electronics.audio.headphone        19739  1655295.71   5.59    1.81
electronics.video.tv               17623  8724539.82   4.99    9.56
appliances.environment.vacuum      15906  2439553.99   4.50    2.67
appliances.kitchen.washer          14163  4923616.33   4.01    5.40
appliances.kitchen.kettle          11869   440466.69   3.36    0.48
computers.peripherals.mouse        10146   252326.27   2.87    0.28

In [93]:
s5=dt.groupby('brand').agg(销量=('buy_cnt','sum'),销售额=('amount','sum'))
s5.sort_values(by='销量',ascending=False,inplace=True)
s5=s5[:10]
s5['销量占比%']=s5.销量/(s5.销量.sum())*100
s5['销售额占比%']=s5.销售额/(s5.销售额.sum())*100
s5

            销量         销售额  销量占比%  销售额占比%
brand
samsung  96110 28918505.95  38.24   38.26
apple    36015 25951286.48  14.33   34.33
ava      26066  1967222.42  10.37    2.60
tefal    17902  1547488.11   7.12    2.05
lg       16669  7803668.62   6.63   10.32
xiaomi   14869  2393106.66   5.92    3.17
philips  12109  1014470.68   4.82    1.34
polaris  10707   433925.31   4.26    0.57
huawei   10668  2219424.36   4.25    2.94
bosch    10189  3340304.32   4.05    4.42

In [96]:
#性别分布
s7=dt[dt['brand']=='samsung'].groupby('sex').agg(人数=('user_id','nunique'))
s7

        人数
sex
女    17543
男    17672

In [97]:
[[index,value]for index,value in s7['人数'].items()]

[['女', 17543], ['男', 17672]]

In [101]:
p7=(Pie()
   .add('',[[index,value]for index,value in s7.人数.items()],
       radius=['30%','45%'],
       label_opts=opts.LabelOpts(position='outside',
                                formatter='{a|{a}}{abg|}\n{hr|}\n{b|{b}:}{c} {per|{d}%}',
                                background_color='#eee',
                                border_color="#aaa",
                                border_width=1,
                                border_radius=4,
                                rich={
                                    "a":{'color':"#999",'linHeight':22,'align':'center'},
                                    "abg": {
                                         "backgroundColor": "#e3e3e3",
                                         "width": "100%",
                                         "align": "right",
                                         "height": 22,
                                         "borderRadius": [4, 4, 0, 0],
                                     },
                                     "hr": {
                                         "borderColor": "#aaa",
                                         "width": "100%",
                                         "borderWidth": 0.5,
                                         "height": 0,
                                     },
                                     "b": {"fontSize": 16, "lineHeight": 33},
                                     "per": {
                                         "color": "#eee",
                                         "backgroundColor": "#334455",
                                         "padding": [2, 4],
                                         "borderRadius": 2,
                                     },
                                },))
   .set_global_opts(title_opts=opts.TitleOpts(title='销量第一的品牌男女特征')))
p7.render_notebook()

In [103]:
s8=dt[dt.brand=='samsung'].groupby('age').agg(人数=('user_id','nunique')).reset_index()

In [106]:
s8.T

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
age,16.00,17.00,18.00,19.00,20.00,21.00,22.00,23.00,24.00,25.00,...,41.00,42.00,43.00,44.00,45.00,46.00,47.00,48.00,49.00,50.00
人数,1007.00,969.00,1036.00,967.00,1067.00,1029.00,992.00,1025.00,1017.00,1043.00,...,1052.00,1035.00,1095.00,1047.00,1051.00,995.00,988.00,1085.00,952.00,1003.00

In [107]:
bins=[15,20,25,30,35,40,45,50]
s8['age_bin']=pd.cut(s8.age,bins=bins)
s8

     age    人数   age_bin
0  16.00  1007  (15, 20]
1  17.00   969  (15, 20]
2  18.00  1036  (15, 20]
3  19.00   967  (15, 20]
4  20.00  1067  (15, 20]
5  21.00  1029  (20, 25]
6  22.00   992  (20, 25]
7  23.00  1025  (20, 25]
8  24.00  1017  (20, 25]
9  25.00  1043  (20, 25]
10 26.00  1005  (25, 30]
11 27.00  1007  (25, 30]
12 28.00  1014  (25, 30]
13 29.00  1014  (25, 30]
14 30.00  1016  (25, 30]
15 31.00   997  (30, 35]
16 32.00  1087  (30, 35]
17 33.00  1002  (30, 35]
18 34.00   938  (30, 35]
19 35.00  1018  (30, 35]
20 36.00  1021  (35, 40]
21 37.00   993  (35, 40]
22 38.00  1008  (35, 40]
23 39.00  1035  (35, 40]
24 40.00   999  (35, 40]
25 41.00  1052  (40, 45]
26 42.00  1035  (40, 45]
27 43.00  1095  (40, 45]
28 44.00  1047  (40, 45]
29 45.00  1051  (40, 45]
30 46.00   995  (45, 50]
31 47.00   988  (45, 50]
32 48.00  1085  (45, 50]
33 49.00   952  (45, 50]
34 50.00  1003  (45, 50]

In [108]:
s9=s8.groupby('age_bin').agg(人数=('人数','sum'))
s9

            人数
age_bin
(15, 20]  5046
(20, 25]  5106
(25, 30]  5056
(30, 35]  5042
(35, 40]  5056
(40, 45]  5280
(45, 50]  5023

In [110]:
p9=(Pie()
   .add('',
       [[str(index)+'岁',value]for index,value in s9['人数'].items()],
       radius=['30%','45%'],
       label_opts=opts.LabelOpts(
           position='outside',
           formatter="{a|{a}}{abg|}\n{hr|}\n {b|{b}: }{c}  {per|{d}%}  ",
            background_color="#eee",
            border_color="#aaa",
            border_width=1,
            border_radius=4,
            rich={
                "a": {"color": "#999", "lineHeight": 22, "align": "center"},
                "abg": {
                    "backgroundColor": "#e3e3e3",
                    "width": "100%",
                    "align": "right",
                    "height": 22,
                    "borderRadius": [4, 4, 0, 0],
                },
                "hr": {
                    "borderColor": "#aaa",
                    "width": "100%",
                    "borderWidth": 0.5,
                    "height": 0,
                },
                "b": {"fontSize": 16, "lineHeight": 33},
                "per": {
                    "color": "#eee",
                    "backgroundColor": "#334455",
                    "padding": [2, 4],
                    "borderRadius": 2,
                },
            },
        ),
    )
   .set_global_opts(title_opts=opts.TitleOpts(title='销量第一的品牌人群年龄特征'),
                   legend_opts=opts.LegendOpts(orient='vertical',pos_top='15%',pos_left='2%')))

p9.render_notebook()

## 用户
计算用户年龄分布  基数/占比  
    计算用户性别分布  基数/占比  
    计算用户地区分布  基数/占比 / 各省用户的占比  
    销售人贡献曲线(找出头部客户重点维护，二八定律-找出累计贡献销售额80%的那批用户)  
    客户消费金额的分位数  
    客户总消费金额的分布  
    单笔订单消费金额的分布  
    新客老客的销售额与销量对比

### 用户年龄分布

In [112]:
s10=dt.groupby('age').agg(人数=('user_id','nunique')).reset_index()
s10

     age    人数
0  16.00  2797
1  17.00  2725
2  18.00  2759
3  19.00  2703
4  20.00  2838
5  21.00  2786
6  22.00  2792
7  23.00  2820
8  24.00  2764
9  25.00  2768
10 26.00  2793
11 27.00  2724
12 28.00  2825
13 29.00  2802
14 30.00  2755
15 31.00  2772
16 32.00  2841
17 33.00  2745
18 34.00  2738
19 35.00  2764
20 36.00  2805
21 37.00  2710
22 38.00  2820
23 39.00  2813
24 40.00  2685
25 41.00  2753
26 42.00  2763
27 43.00  2875
28 44.00  2854
29 45.00  2784
30 46.00  2713
31 47.00  2677
32 48.00  2781
33 49.00  2707
34 50.00  2724

In [118]:
bins=[15,20,25,30,35,40,45,50]
s10['age_bin']=pd.cut(s10.age,bins=bins)
s10.age.astype('int64')
s10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   age      35 non-null     float64
 1   人数       35 non-null     int64
 2   age_bin  35 non-null     category
dtypes: category(1), float64(1), int64(1)
memory usage: 1.1 KB

### 用户性别分布

In [119]:
s11=dt.groupby('sex').agg(人数=('user_id','nunique'))
s11

        人数
sex
女    47235
男    47628

In [122]:
p11=(Pie()
    .add('性别人数',
        [[index,value] for index,value in s11.人数.items()],
        radius=[70,110],
        label_opts=opts.LabelOpts(position='middle'),)
    .set_global_opts(title_opts=opts.TitleOpts('用户性别特征'),
                    legend_opts=opts.LegendOpts(pos_top='40%',pos_left='2%',orient='vertical')))
p11.render_notebook()

### 用户地区分布

In [124]:
s12=dt.groupby('local').agg(人数=('user_id','nunique')).sort_values('人数',ascending=False)
s12

          人数
local
广东     21382
上海     16031
北京     15928
江苏      5561
海南      5449
四川      5445
浙江      5370
湖北      5355
重庆      5342
天津      5337
湖南      5330

In [125]:
p12 = (
    Pie()
    .add(
        "",
        [[index,value] for index,value in s12['人数'].items()],
        radius=["30%", "55%"],
        label_opts=opts.LabelOpts(
            position="outside",
            formatter="{a|{a}}{abg|}\n{hr|}\n {b|{b}: }{c}  {per|{d}%}  ",
            background_color="#eee",
            border_color="#aaa",
            border_width=1,
            border_radius=4,
            rich={
                "a": {"color": "#999", "lineHeight": 22, "align": "center"},
                "abg": {
                    "backgroundColor": "#e3e3e3",
                    "width": "100%",
                    "align": "right",
                    "height": 22,
                    "borderRadius": [4, 4, 0, 0],
                },
                "hr": {
                    "borderColor": "#aaa",
                    "width": "100%",
                    "borderWidth": 0.5,
                    "height": 0,
                },
                "b": {"fontSize": 16, "lineHeight": 33},
                "per": {
                    "color": "#eee",
                    "backgroundColor": "#334455",
                    "padding": [2, 4],
                    "borderRadius": 2,
                },
            },
        ),
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(title="用户地区分布"),
        toolbox_opts=opts.ToolboxOpts(is_show=True),
        legend_opts=opts.LegendOpts(orient="vertical", pos_top="15%", pos_left="2%"),
    )
    
)
p12.render_notebook()

### 用户销售贡献曲线

In [128]:
s13=dt.groupby('user_id').agg(消费金额=('amount','sum'))
s13.sort_values('消费金额',ascending=False,inplace=True)
s13['累计消费总额']=s13.消费金额.cumsum()
s13['累计消费占比%']=s13.累计消费总额/s13.消费金额.sum()*100
s13['rank']=s13.消费金额.rank(ascending=False)
s13['rank']=s13['rank'].astype('int64')
s13['累计用户占比%']=s13['rank']/s13['rank'].max()*100
s13

                         消费金额       累计消费总额  累计消费占比%   rank  累计用户占比%
user_id
1515915625512422912 160604.07    160604.07     0.14      1     0.00
1515915625513695488 158277.37    318881.44     0.28      2     0.00
1515915625512377088 149967.06    468848.50     0.41      3     0.00
1515915625513577472 135672.84    604521.34     0.53      4     0.00
1515915625514597888 133945.88    738467.22     0.64      5     0.01
...                       ...          ...      ...    ...      ...
1515915625511079936      0.02 114986635.82   100.00  92743    99.99
1515915625450548736      0.02 114986635.84   100.00  92743    99.99
1515915625506653440      0.02 114986635.86   100.00  92743    99.99
1515915625451367168      0.02 114986635.88   100.00  92743    99.99
1515915625468531712      0.00 114986635.88   100.00  92755   100.00

[92755 rows x 5 columns]

In [132]:
x=[round(x,2)for x in s13['累计用户占比%'][::1000]]
y=[round(x,2)for x in s13['累计消费占比%'][::1000]]

p13=(Line()
    .add_xaxis(x)
    .add_yaxis('前%客户贡献%销售额',y,
              symbol='emptyCircle',
              is_symbol_show=True,
              is_smooth=True,
              label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(tooltip_opts=opts.TooltipOpts(is_show=True),
                    xaxis_opts=opts.AxisOpts(type_='category',
                                            axistick_opts=opts.AxisTickOpts(is_show=True),
                                            splitline_opts=opts.SplitLineOpts(is_show=True)),
                    yaxis_opts=opts.AxisOpts(type_='value',
                                            axistick_opts=opts.AxisTickOpts(is_show=True),
                                            splitline_opts=opts.SplitLineOpts(is_show=True))))

p13.render_notebook()

### 二八贡献
找出头部客户重点维护，二八定律，找出累计贡献销售额80%的那批用户

In [133]:
s14=s13[s13.累计消费总额/(s13.消费金额.sum()) <0.8].reset_index()

In [135]:
data14=s14.shape[0]/dt.user_id.nunique()*100
data14

27.39259339119185

#### 结论前27.39%贡献了80%的销售额，这些客户重点维护

### 客户总消费金额的分位数

In [136]:
s15=dt.groupby('user_id').agg(消费金额=('amount','sum')).describe(percentiles=[0.01,0.1,0.25,0.5,0.75,0.90,0.99])
s15

           消费金额
count  92755.00
mean    1239.68
std     4129.72
min        0.00
1%         6.00
10%       41.64
25%      148.11
50%      456.89
75%     1141.17
90%     2402.53
99%    12744.87
max   160604.07

In [137]:
from pyecharts.charts import Funnel

In [138]:
p14=(Funnel()
    .add('消费金额',[list(z) for z in zip(s15.index,s15.消费金额.values)][4:-1],label_opts=opts.LabelOpts(position='inside'))
    .set_global_opts(title_opts=opts.TitleOpts(title='客户消费金额情况'),
                    ))
p14.render_notebook()

### 客户总消费金额的分布

In [139]:
s16=dt.groupby('user_id').agg(消费金额=('amount','sum')).reset_index()
bins=[0,10,20,50,100,150,200,500,1000,2000,5000,10000,100000,1000000]
s16['cost_bin']=pd.cut(s16['消费金额'],bins=bins)
s16

                   user_id    消费金额       cost_bin
0      1515915625439951872  416.64     (200, 500]
1      1515915625440038400   56.43      (50, 100]
2      1515915625440051712 7489.53  (5000, 10000]
3      1515915625440099840 4929.86   (2000, 5000]
4      1515915625440121600  182.83     (150, 200]
...                    ...     ...            ...
92750  1515915625514887424  208.31     (200, 500]
92751  1515915625514887936 3472.20   (2000, 5000]
92752  1515915625514888704  752.49    (500, 1000]
92753  1515915625514891008  925.67    (500, 1000]
92754  1515915625514891264  418.96     (200, 500]

[92755 rows x 3 columns]

In [140]:
s16_data=s16.groupby('cost_bin').agg(人数=('user_id','nunique')).reset_index()
s16_data

             cost_bin     人数
0             (0, 10]   1637
1            (10, 20]   2616
2            (20, 50]   6692
3           (50, 100]   6345
4          (100, 150]   5993
5          (150, 200]   4684
6          (200, 500]  20658
7         (500, 1000]  18074
8        (1000, 2000]  14294
9        (2000, 5000]   8709
10      (5000, 10000]   1859
11    (10000, 100000]   1176
12  (100000, 1000000]     17

In [147]:
p16=(Bar(init_opts=opts.InitOpts(theme='dark'))
    .add_xaxis([str(x)+'元' for x in s16_data.cost_bin])
    .add_yaxis('',s16_data.人数.tolist())
    .set_global_opts(title_opts=opts.TitleOpts(title='客户总消费金额的分布'),
                    xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=25)),
                    yaxis_opts=opts.AxisOpts(name='人数',axislabel_opts=opts.LabelOpts(formatter='{value}人')),
                    brush_opts=opts.BrushOpts()))
p16.render_notebook()

### 单笔订单消费金额分布

In [148]:
bins=[0,10,20,50,100,150,200,500,1000,2000,5000,10000,100000]
s17=dt[['order_id','amount']].copy()
s17['cost_bin']=pd.cut(s17.amount,bins=bins)
s17

                   order_id  amount       cost_bin
0       2294359932054536986  324.02     (200, 500]
1       2294444024058086220  155.04     (150, 200]
2       2294584263154074236  217.57     (200, 500]
3       2295716521449619559   39.33       (20, 50]
4       2295740594749702229 5548.04  (5000, 10000]
...                     ...     ...            ...
535060  2388440981134693942  138.87     (100, 150]
535061  2388440981134693943  418.96     (200, 500]
535062  2388440981134693944   12.48       (10, 20]
535063  2388440981134693944   41.64       (20, 50]
535064  2388440981134693944   53.22      (50, 100]

[535065 rows x 3 columns]

In [149]:
s17_data=s17.groupby('cost_bin').agg(订单数量=('order_id','count')).reset_index()
s17_data

           cost_bin    订单数量
0           (0, 10]   66601
1          (10, 20]   47449
2          (20, 50]   94675
3         (50, 100]   59528
4        (100, 150]   49162
5        (150, 200]   33235
6        (200, 500]  117926
7       (500, 1000]   52013
8      (1000, 2000]   13450
9      (2000, 5000]     972
10    (5000, 10000]      22
11  (10000, 100000]       2

In [171]:
p17=(Bar()
    .add_xaxis([str(x)+'元' for x in s17_data.cost_bin])
    .add_yaxis('订单数量',[x for x in s17_data.订单数量])
    .set_global_opts(xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=25)),
                    title_opts=opts.TitleOpts(title='单笔订单消费金额的分布')))
p17.render_notebook()

### 新老顾客销售额与销量对比

In [155]:
a=dt.groupby('user_id').agg(首购时间=('date','min')).reset_index()

In [156]:
a

                   user_id       首购时间
0      1515915625439951872 2020-07-09
1      1515915625440038400 2020-09-22
2      1515915625440051712 2020-10-23
3      1515915625440099840 2020-05-21
4      1515915625440121600 2020-05-16
...                    ...        ...
92750  1515915625514887424 2020-11-21
92751  1515915625514887936 2020-11-21
92752  1515915625514888704 2020-11-21
92753  1515915625514891008 2020-11-21
92754  1515915625514891264 2020-11-21

[92755 rows x 2 columns]

In [158]:
s17=pd.merge(dt,a,how='inner',on='user_id')
s17['新老顾客']=np.where(s17['首购时间']==s17.date,'新顾客','老顾客')
s17.head()

,order_id,product_id,category_id,category_code,brand,price,user_id,age,sex,local,date,month,hour,weekday,buy_cnt,amount,首购时间,新老顾客
0,2294359932054536986,1515966223509089906,2268105426648171520,electronics.tablet,samsung,162.01,1515915625441993984,24.00,女,海南,2020-04-24,4,11,5,2,324.02,2020-04-24,新顾客
1,2294444024058086220,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京,2020-04-24,4,14,5,2,155.04,2020-04-24,新顾客
2,2297951447913857849,2273948319057183658,2268105430162997248,electronics.audio.headphone,huawei,77.52,1515915625447879424,38.00,女,北京,2020-04-29,4,10,3,1,77.52,2020-04-24,老顾客
3,2297951447913857849,1515966223509088613,2268105430162997248,electronics.audio.headphone,apple,203.68,1515915625447879424,38.00,女,北京,2020-04-29,4,10,3,1,203.68,2020-04-24,老顾客
4,2388440981134625996,1515966223517999094,2268105407220155904,computers.notebook,apple,2342.57,1515915625447879424,38.00,女,北京,2020-10-21,10,19,3,1,2342.57,2020-04-24,老顾客

In [161]:
s18=s17[s17['新老顾客']=='新顾客'].groupby('month').agg(新顾客人数=('新老顾客','count'))
s18

       新顾客人数
month
1       6238
2       5796
3       4902
4       5831
5      20399
6      14919
7      36482
8      39121
9      16877
10     51755
11     27324

In [163]:
s18['老顾客人数']=s17[s17['新老顾客']=='老顾客'].groupby('month').agg(老顾客人数=('新老顾客','count'))
s18['新顾客人数占比%']=s18['新顾客人数']/(s18['新顾客人数']+s18['老顾客人数'])*100
s18['老顾客人数占比%']=s18['老顾客人数']/(s18['新顾客人数']+s18['老顾客人数'])*100
s18['新客销量']=s17[s17['新老顾客']=='新顾客'].groupby('month').agg(新客销量=('buy_cnt','sum'))
s18['老客销量']=s17[s17['新老顾客']=='老顾客'].groupby('month').agg(老客销量=('buy_cnt','sum'))
s18

       新顾客人数  老顾客人数  新顾客人数占比%  老顾客人数占比%   新客销量   老客销量
month
1       6238   7211     46.38     53.62   6238   7211
2       5796  11152     34.20     65.80   5796  11152
3       4902  12765     27.75     72.25   4902  12765
4       5831   5501     51.46     48.54   5843   5505
5      20399  18176     52.88     47.12  20450  18216
6      14919  24198     38.14     61.86  14932  24215
7      36482  36763     49.81     50.19  36563  36841
8      39121  56856     40.76     59.24  39161  56923
9      16877  50379     25.09     74.91  16890  50419
10     51755  46292     52.79     47.21  51775  46416
11     27324  36128     43.06     56.94  27336  36150

In [164]:
s18['新客销售额']=s17[s17['新老顾客']=='新顾客'].groupby('month').agg(新客销售额=('amount','sum'))
s18['老客销售额']=s17[s17['新老顾客']=='老顾客'].groupby('month').agg(老客销售额=('amount','sum'))
s18=s18.reset_index()
s18

,month,新顾客人数,老顾客人数,新顾客人数占比%,老顾客人数占比%,新客销量,老客销量,新客销售额,老客销售额
0,1,6238,7211,46.38,53.62,6238,7211,778012.42,951452.51
1,2,5796,11152,34.20,65.80,5796,11152,883213.42,1333458.89
2,3,4902,12765,27.75,72.25,4902,12765,822957.39,2018058.19
3,4,5831,5501,51.46,48.54,5843,5505,883094.19,791356.49
4,5,20399,18176,52.88,47.12,20450,18216,4486959.03,3170373.48
5,6,14919,24198,38.14,61.86,14932,24215,3578852.71,3910459.61
6,7,36482,36763,49.81,50.19,36563,36841,8415359.99,7633448.00
7,8,39121,56856,40.76,59.24,39161,56923,12313534.93,15067364.73
8,9,16877,50379,25.09,74.91,16890,50419,5300792.31,11496340.30
9,10,51755,46292,52.79,47.21,51775,46416,9125148.62,10251424.13
10,11,27324,36128,43.06,56.94,27336,36150,4983194.17,6791780.37

In [173]:
p18=(Bar()
    .add_xaxis([str(x)+'月' for x in s18.month])
    .add_yaxis('新客销量(件)',[x for x in s18.新客销量],stack='stack1')
    .add_yaxis('老客销量(件)',[x for x in s18.老客销量],stack='stack1')
    .add_yaxis('新客销售额(元)',[round(x,2) for x in s18.新客销售额],stack='stack2')
    .add_yaxis('老客销售额(元)',[round(x,2) for x in s18.老客销售额],stack='stack2')
    #.extend_axis(yaxis=opts.AxisOpts)
    .set_global_opts(title_opts=opts.TitleOpts(title='新客老客的销售额与销量对比')))
p18.render_notebook()

In [179]:
p18=(Bar()
    .add_xaxis([str(x)+'月' for x in s18.month])
    .add_yaxis('新客销量(件)',[x for x in s18.新客销量],stack='stack1')
    .add_yaxis('老客销量(件)',[x for x in s18.老客销量],stack='stack1')
    .add_yaxis('新客销售额(元)',[round(x,2) for x in s18.新客销售额],stack='stack2')
    .add_yaxis('老客销售额(元)',[round(x,2) for x in s18.老客销售额],stack='stack2')
    .set_global_opts(title_opts=opts.TitleOpts(title='新客老客的销售额与销量对比'),
                    legend_opts=opts.LegendOpts(pos_left='30%'))
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False)))
p18.render_notebook()

## 用户影响  评分

### 年龄区分 订单数量/订单总额/单均价

In [181]:
user_order=dt.groupby('user_id').agg(订单数量=('order_id','nunique'),订单总额=('amount','sum')).reset_index()
user_order['客单均价']=round(user_order.订单总额/user_order.订单数量,2)
user_order

                   user_id  订单数量    订单总额    客单均价
0      1515915625439951872     1  416.64  416.64
1      1515915625440038400     2   56.43   28.22
2      1515915625440051712     4 7489.53 1872.38
3      1515915625440099840    16 4929.86  308.12
4      1515915625440121600     2  182.83   91.42
...                    ...   ...     ...     ...
92750  1515915625514887424     1  208.31  208.31
92751  1515915625514887936     1 3472.20 3472.20
92752  1515915625514888704     3  752.49  250.83
92753  1515915625514891008     1  925.67  925.67
92754  1515915625514891264     1  418.96  418.96

[92755 rows x 4 columns]

In [184]:
user_data=dt[['user_id','age','sex','local']]
user_data

                    user_id   age sex local
0       1515915625441993984 24.00   女    海南
1       1515915625447879424 38.00   女    北京
2       1515915625443148032 32.00   女    广东
3       1515915625450382848 20.00   男    重庆
4       1515915625448766464 21.00   男    北京
...                     ...   ...  ..   ...
535060  1515915625514888704 21.00   男    上海
535061  1515915625514891264 21.00   女    北京
535062  1515915625514834176 19.00   女    上海
535063  1515915625514834176 19.00   女    上海
535064  1515915625514834176 19.00   女    上海

[535065 rows x 4 columns]

In [186]:
user_data=pd.merge(user_order,user_data,how='inner',on='user_id')
user_data.drop_duplicates('user_id',inplace=True)
user_data.reset_index()
user_data

                    user_id  订单数量    订单总额    客单均价   age sex local   age_bin
0       1515915625439951872     1  416.64  416.64 33.00   女    浙江  (30, 35]
1       1515915625440038400     2   56.43   28.22 31.00   男    北京  (30, 35]
3       1515915625440051712     4 7489.53 1872.38 39.00   男    广东  (35, 40]
16      1515915625440099840    16 4929.86  308.12 44.00   男    天津  (40, 45]
36      1515915625440121600     2  182.83   91.42 40.00   女    北京  (35, 40]
...                     ...   ...     ...     ...   ...  ..   ...       ...
535058  1515915625514887424     1  208.31  208.31 16.00   男    江苏  (15, 20]
535059  1515915625514887936     1 3472.20 3472.20 33.00   女    广东  (30, 35]
535060  1515915625514888704     3  752.49  250.83 21.00   男    上海  (20, 25]
535063  1515915625514891008     1  925.67  925.67 27.00   女    上海  (25, 30]
535064  1515915625514891264     1  418.96  418.96 21.00   女    北京  (20, 25]

[92755 rows x 8 columns]

In [187]:
bins=[15,20,25,30,35,40,45,50]
user_data['age_bin']=pd.cut(user_data.age,bins=bins)
user_data

                    user_id  订单数量    订单总额    客单均价   age sex local   age_bin
0       1515915625439951872     1  416.64  416.64 33.00   女    浙江  (30, 35]
1       1515915625440038400     2   56.43   28.22 31.00   男    北京  (30, 35]
3       1515915625440051712     4 7489.53 1872.38 39.00   男    广东  (35, 40]
16      1515915625440099840    16 4929.86  308.12 44.00   男    天津  (40, 45]
36      1515915625440121600     2  182.83   91.42 40.00   女    北京  (35, 40]
...                     ...   ...     ...     ...   ...  ..   ...       ...
535058  1515915625514887424     1  208.31  208.31 16.00   男    江苏  (15, 20]
535059  1515915625514887936     1 3472.20 3472.20 33.00   女    广东  (30, 35]
535060  1515915625514888704     3  752.49  250.83 21.00   男    上海  (20, 25]
535063  1515915625514891008     1  925.67  925.67 27.00   女    上海  (25, 30]
535064  1515915625514891264     1  418.96  418.96 21.00   女    北京  (20, 25]

[92755 rows x 8 columns]

### 标准归一化评分

In [188]:
def score_c(x):
    score=(x.values-x.min())/(x.max()-x.min())
    return score

### Z-标准化

In [189]:
def score_z(x):
    score=(x.values-x.mean())/x.std()
    return score

In [195]:
s20=user_data.groupby('age_bin').agg(订单数量=('订单数量','sum'),订单总额=('订单总额','sum'),客单均价=('客单均价','mean'),客均单量=('订单数量','mean')).reset_index()

In [192]:
s20

    age_bin   订单数量        订单总额       客单均价  客均单量
0  (15, 20]  55148 16117561.58 4199466.12  4.18
1  (20, 25]  55703 16599359.90 4249192.85  4.17
2  (25, 30]  55160 16608612.57 4248857.70  4.15
3  (30, 35]  58522 17075999.66 4219793.72  4.42
4  (35, 40]  49641 14986001.86 4223562.25  3.74
5  (40, 45]  58562 16939977.76 4239818.51  4.37
6  (45, 50]  56006 16659122.55 4178717.63  4.30

In [196]:
score1=score_c(s20.订单数量)
score2=score_c(s20.订单总额)
score3=score_c(s20.客单均价)
score4=score_c(s20.客均单量)
s20['score']=score1+score2+score3+score4
s20['购买力rank']=s20['score'].rank(ascending=False)
s20.sort_values(by='购买力rank')

    age_bin   订单数量        订单总额   客单均价  客均单量  score  购买力rank
3  (30, 35]  58522 17075999.66 318.50  4.42   3.46     1.00
6  (45, 50]  56006 16659122.55 320.87  4.30   3.34     2.00
5  (40, 45]  58562 16939977.76 316.40  4.37   2.87     3.00
2  (25, 30]  55160 16608612.57 319.75  4.15   2.75     4.00
1  (20, 25]  55703 16599359.90 318.43  4.17   2.55     5.00
0  (15, 20]  55148 16117561.58 318.67  4.18   2.32     6.00
4  (35, 40]  49641 14986001.86 318.21  3.74   0.40     7.00

### 性别区分 销量/销售额/客单价

In [197]:
s21=user_data.groupby('sex').agg(订单数量=('订单数量','sum'),订单总额=('订单总额','sum'),客单均价=('客单均价','mean'),客均单量=('订单数量','mean')).reset_index()

In [198]:
s21

  sex    订单数量        订单总额   客单均价  客均单量
0   女  192949 57379012.61 319.08  4.17
1   男  195793 57607623.27 318.28  4.21

### 地区区分 销量/销售额/客单价

In [199]:
s22=user_data.groupby('local').agg(订单数量=('订单数量','sum'),订单总额=('订单总额','sum'),客单均价=('客单均价','mean'),客均单量=('订单数量','mean')).reset_index()
score1=score_c(s22.订单数量)
score2=score_c(s22.订单总额)
score3=score_c(s22.客单均价)
score4=score_c(s22.客均单量)
s22['score']=score1+score2+score3+score4
s22['购买力rank']=s22['score'].rank(ascending=False)
s22.sort_values(by='购买力rank')

   local   订单数量        订单总额   客单均价  客均单量  score  购买力rank
4     广东  84851 25484871.70 318.15  4.11   2.91     1.00
0     上海  66350 19596287.53 319.19  4.30   2.58     2.00
1     北京  64483 18897882.44 318.43  4.19   2.36     3.00
3     天津  20788  6340586.69 327.10  4.06   1.48     4.00
7     海南  23076  6714984.76 318.69  4.43   1.36     5.00
9     湖南  23680  6770405.16 311.26  4.65   1.12     6.00
6     浙江  20712  6152130.18 321.81  4.03   1.11     7.00
8     湖北  18655  5842968.75 327.20  3.62   1.00     8.00
5     江苏  21232  6279389.24 320.07  3.99   0.97     9.00
2     四川  23070  6621265.34 312.02  4.44   0.95    10.00
10    重庆  21845  6285864.09 312.61  4.27   0.79    11.00

## 时间
  客户消费周期分布情况  
    按周销量/销售额分布  
    按小时分析  
    每月复购率

In [200]:
s_all=dt.groupby('date').agg(销量=('buy_cnt','sum'),销售额=('amount','sum'))
s_all.head()

             销量      销售额
date
2020-01-05  580 77216.52
2020-01-06  565 61146.03
2020-01-07  706 82381.21
2020-01-08  446 56344.74
2020-01-09  449 58278.71

In [203]:
p_a=(Line()
    .add_xaxis([x.strftime('%m-%d')for x in s_all.index.tolist()])
    .add_yaxis('销售额(万)',[round(x/10000,2)for x in s_all.销售额])
    .add_yaxis('销量(件)',s_all.销量.tolist(),yaxis_index=1)
    .extend_axis(yaxis=opts.AxisOpts(axislabel_opts=opts.LabelOpts(formatter='{value}件',interval=50)))
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(tooltip_opts=opts.TooltipOpts(trigger='axis'),
                    title_opts=opts.TitleOpts(title='销售额与销量的整体走势',subtitle='。。。'),
                    yaxis_opts=opts.AxisOpts(name='金额(单位:万)',axislabel_opts=opts.LabelOpts(formatter='{value}万')),
                    datazoom_opts=opts.DataZoomOpts(is_show=True)))

p_a.render_notebook()

### 客户消费周期分布情况

In [204]:
s23=dt[dt['amount']>0].sort_values('date').groupby('user_id').apply(lambda x:x['date']-x['date'].shift()).dt.days

In [208]:
s23[s23>0].describe(percentiles=[0.01,0.1,0.25,0.75,0.9,0.99])

count   139989.00
mean        21.06
std         31.44
min          1.00
1%           1.00
10%          1.00
25%          2.00
50%          7.00
75%         26.00
90%         63.00
99%        146.00
max        299.00
Name: date, dtype: float64

### 按周销量/销售额分布

In [210]:
s24=dt.groupby('weekday').agg(销量=('buy_cnt','sum'),销售额=('amount','sum')).reset_index()
s24

   weekday     销量         销售额
0        0  80504 17242028.49
1        1  72092 16238608.52
2        2  75109 16139181.01
3        3  76477 15911125.53
4        4  74558 15481679.91
5        5  70491 15730500.45
6        6  86468 18243511.97

In [211]:
s25=dt.groupby('hour').agg(销量=('buy_cnt','sum'),销售额=('amount','sum')).reset_index()
s25

    hour     销量         销售额
0      0   3217   886468.18
1      1   4243  1142678.49
2      2   6675  1814292.03
3      3  12465  3291307.12
4      4  25169  5303495.98
5      5  38115  7706593.96
6      6  44697  8986304.31
7      7  47254  9417942.55
8      8  48585  9659576.28
9      9  50282 10252409.67
10    10  50217  9916102.26
11    11  46433  9326238.33
12    12  40651  8158960.06
13    13  32622  6884993.36
14    14  21944  5197196.36
15    15  16640  4201274.81
16    16  12862  3623666.01
17    17  10655  2905758.77
18    18   7422  2041290.30
19    19   4662  1290724.54
20    20   3147   869196.73
21    21   2267   670043.50
22    22   2567   681566.81
23    23   2908   758555.47

### 每月新客，老客人数分析
老客定义：首次购买次月即成为老客

In [214]:
s26_data=dt.groupby('user_id').agg(首次购买月份=('month','min')).reset_index()
s26_data=pd.merge(dt,s26_data,how='inner',on='user_id')
s26_data['月新老客户']=np.where(s26_data['month']==s26_data['首次购买月份'],'新客户','老客户')

In [216]:
s26=s26_data[s26_data.月新老客户=='新客户'].groupby('month').agg(新客户数量=('月新老客户','count'))
s26['老客户数量']=s26_data[s26_data.月新老客户=='老客户'].groupby('month').agg(老客户数量=('月新老客户','count'))
s26

       新客户数量    老客户数量
month
1      13449      NaN
2      12215  4733.00
3      11371  6296.00
4       8209  3123.00
5      27070 11505.00
6      18640 20477.00
7      50076 23169.00
8      55475 40502.00
9      26723 40533.00
10     63246 34801.00
11     39158 24294.00

In [217]:
s26['新客户占比']=s26['新客户数量']/(s26['新客户数量']+s26['老客户数量'])*100
s26['老客户占比']=s26['老客户数量']/(s26['新客户数量']+s26['老客户数量'])*100

In [220]:
p26=(Bar(init_opts=opts.InitOpts(theme='infographic'))
    .add_xaxis([str(x)+'月' for x in s26.index])
    .add_yaxis('新客户数量',[x for x in s26.新客户数量],stack='stack1')
    .add_yaxis('老客户数量',[x for x in s26.老客户数量],stack='stack1')
    .add_yaxis('新客户占比%',[round(x,2)for x in s26.新客户占比],stack='stack2')
    .add_yaxis('老客户占比%',[round(x,2)for x in s26.老客户占比],stack='stack2')
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(title_opts=opts.TitleOpts(title='每月新老客户对比')))
p26.render_notebook()

### 每月新用户/新用户销量/新用户销售额/环比

In [221]:
s27=s26_data[s26_data['月新老客户']=='新客户'].groupby('month').agg(新用户数量=('月新老客户','count'),新用户销量=('buy_cnt','sum'),新用户销售额=('amount','sum')).reset_index()

In [223]:
s27['新用户数量环比增长']=s27.新用户数量.diff()
s27['新用户数量环比增长率%']=s27.新用户数量.pct_change()*100
s27['新用户销量环比增长']=s27.新用户销量.diff()
s27['新用户销量环比增长率%']=s27.新用户销量.pct_change()*100
s27['新用户销售额环比增长']=s27.新用户销售额.diff()
s27['新用户销售额环比增长率%']=s27.新用户销售额.pct_change()*100

In [224]:
s27

,month,新用户数量,新用户销量,新用户销售额,新用户数量环比增长,新用户数量环比增长率%,新用户销量环比增长,新用户销量环比增长率%,新用户销售额环比增长,新用户销售额环比增长率%
0,1,13449,13449,1729464.93,NaN,NaN,NaN,NaN,NaN,NaN
1,2,12215,12215,1710658.45,-1234.00,-9.18,-1234.00,-9.18,-18806.48,-1.09
2,3,11371,11371,1934702.29,-844.00,-6.91,-844.00,-6.91,224043.84,13.10
3,4,8209,8221,1214789.79,-3162.00,-27.81,-3150.00,-27.70,-719912.50,-37.21
4,5,27070,27143,5793011.10,18861.00,229.76,18922.00,230.17,4578221.31,376.87
5,6,18640,18655,4383038.68,-8430.00,-31.14,-8488.00,-31.27,-1409972.42,-24.34
6,7,50076,50192,11668313.82,31436.00,168.65,31537.00,169.05,7285275.14,166.22
7,8,55475,55533,17503323.05,5399.00,10.78,5341.00,10.64,5835009.23,50.01
8,9,26723,26745,8248995.19,-28752.00,-51.83,-28788.00,-51.84,-9254327.86,-52.87
9,10,63246,63289,11695494.47,36523.00,136.67,36544.00,136.64,3446499.28,41.78
10,11,39158,39171,7104580.63,-24088.00,-38.09,-24118.00,-38.11,-4590913.84,-39.25

# RFM模型
R：最近一次消费（Recency）  
F：消费频率（Frequency）(按天)  
M：消费金额（Monetary）

In [259]:
rfm=dt.groupby(['user_id','date']).agg(消费金额=('amount','sum')).reset_index()

In [260]:
rfm

                    user_id       date    消费金额
0       1515915625439951872 2020-07-09  416.64
1       1515915625440038400 2020-09-22   21.04
2       1515915625440038400 2020-10-28   35.39
3       1515915625440051712 2020-10-23  972.16
4       1515915625440051712 2020-11-16 6517.37
...                     ...        ...     ...
232744  1515915625514887424 2020-11-21  208.31
232745  1515915625514887936 2020-11-21 3472.20
232746  1515915625514888704 2020-11-21  752.49
232747  1515915625514891008 2020-11-21  925.67
232748  1515915625514891264 2020-11-21  418.96

[232749 rows x 3 columns]

In [261]:
rfm=rfm.groupby('user_id').agg(最后消费日期=('date','max'),F=('date','count'),M=('消费金额','sum'))

In [262]:
rfm

                        最后消费日期   F       M
user_id
1515915625439951872 2020-07-09   1  416.64
1515915625440038400 2020-10-28   2   56.43
1515915625440051712 2020-11-16   2 7489.53
1515915625440099840 2020-11-08  12 4929.86
1515915625440121600 2020-07-14   2  182.83
...                        ...  ..     ...
1515915625514887424 2020-11-21   1  208.31
1515915625514887936 2020-11-21   1 3472.20
1515915625514888704 2020-11-21   1  752.49
1515915625514891008 2020-11-21   1  925.67
1515915625514891264 2020-11-21   1  418.96

[92755 rows x 3 columns]

In [263]:
rfm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 92755 entries, 1515915625439951872 to 1515915625514891264
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   最后消费日期  92755 non-null  datetime64[ns]
 1   F       92755 non-null  int64
 2   M       92755 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 2.8 MB

In [264]:
rfm['最后消费日期']=pd.to_datetime(rfm.最后消费日期)

In [265]:
rfm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 92755 entries, 1515915625439951872 to 1515915625514891264
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   最后消费日期  92755 non-null  datetime64[ns]
 1   F       92755 non-null  int64
 2   M       92755 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 2.8 MB

In [266]:
rfm['R']=(rfm['最后消费日期'].apply(lambda x:rfm.最后消费日期.max()-x)).dt.days

In [267]:
rfm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 92755 entries, 1515915625439951872 to 1515915625514891264
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   最后消费日期  92755 non-null  datetime64[ns]
 1   F       92755 non-null  int64
 2   M       92755 non-null  float64
 3   R       92755 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 3.5 MB

In [270]:
rfm

                        最后消费日期   F       M    R
user_id
1515915625439951872 2020-07-09   1  416.64  135
1515915625440038400 2020-10-28   2   56.43   24
1515915625440051712 2020-11-16   2 7489.53    5
1515915625440099840 2020-11-08  12 4929.86   13
1515915625440121600 2020-07-14   2  182.83  130
...                        ...  ..     ...  ...
1515915625514887424 2020-11-21   1  208.31    0
1515915625514887936 2020-11-21   1 3472.20    0
1515915625514888704 2020-11-21   1  752.49    0
1515915625514891008 2020-11-21   1  925.67    0
1515915625514891264 2020-11-21   1  418.96    0

[92755 rows x 4 columns]

In [239]:
rfm.describe(percentiles=(0.01,0.1,0.25,0.75,0.9,0.95,0.99))

             F         M        R
count 92755.00  92755.00 92755.00
mean      2.51   1239.68    98.59
std       4.56   4129.72    54.53
min       1.00      0.00     0.00
1%        1.00      6.00     2.00
10%       1.00     41.64    24.00
25%       1.00    148.11    61.00
50%       1.00    456.89   101.00
75%       3.00   1141.17   127.00
90%       4.00   2402.53   180.00
95%       6.00   3823.67   196.00
99%      17.00  12744.87   211.00
max     159.00 160604.07   321.00

In [252]:
rfm2=rfm[['R','F','M']].reset_index(drop=True)

In [253]:
rfm2

         R   F       M
0      135   1  416.64
1       24   2   56.43
2        5   2 7489.53
3       13  12 4929.86
4      130   2  182.83
...    ...  ..     ...
92750    0   1  208.31
92751    0   1 3472.20
92752    0   1  752.49
92753    0   1  925.67
92754    0   1  418.96

[92755 rows x 3 columns]

In [254]:
def rfm_func(x):
    level=x.map(lambda x:'1'if x >=0 else '0')
    label=level.R+level.F+level.M
    d={
        '111':'重要价值客户',
        '011':'重要保持客户',
        '101':'重要挽留客户',
        '001':'重要发展客户',
        '110':'一般价值客户',
        '010':'一般保持客户',
        '100':'一般挽留客户',
        '000':'一般发展客户',
    }
    result=d[label]
    return result

rfm2['label']=rfm2.apply(lambda x:x-x.mean()).apply(rfm_func,axis=1)
rfm2

         R   F       M   label
0      135   1  416.64  一般挽留客户
1       24   2   56.43  一般发展客户
2        5   2 7489.53  重要发展客户
3       13  12 4929.86  重要保持客户
4      130   2  182.83  一般挽留客户
...    ...  ..     ...     ...
92750    0   1  208.31  一般发展客户
92751    0   1 3472.20  重要发展客户
92752    0   1  752.49  一般发展客户
92753    0   1  925.67  一般发展客户
92754    0   1  418.96  一般发展客户

[92755 rows x 4 columns]

In [255]:
rfm2['label'].value_counts()

一般挽留客户    39391
一般发展客户    21386
重要保持客户    11049
一般保持客户     7201
重要发展客户     4378
一般价值客户     3638
重要挽留客户     3397
重要价值客户     2315
Name: label, dtype: int64

# 用户画像

In [249]:
user_p1=dt.groupby('user_id')['weekday'].agg(lambda x:x.mode().values[0])
user_p2=dt.groupby('user_id')['hour'].agg(lambda x:x.mode().values[0])
user_p3=dt.groupby('user_id')['category_code'].agg(lambda x:x.mode().values[0])
user_p4=dt.groupby('user_id')['brand'].agg(lambda x:x.mode().values[0])
user_p5=dt.groupby('user_id').agg(buy_cnt=('buy_cnt','sum'),amount=('amount','sum'))

In [250]:
user_p=pd.concat([user_p1,user_p2,user_p3,user_p4,user_p5],axis=1).reset_index()
user_p

,user_id,weekday,hour,category_code,brand,buy_cnt,amount
0,1515915625439951872,4,6,electronics.video.tv,lg,1,416.64
1,1515915625440038400,2,5,computers.network.router,asus,2,56.43
2,1515915625440051712,1,15,electronics.smartphone,apple,13,7489.53
3,1515915625440099840,5,9,R,nordland,21,4929.86
4,1515915625440121600,2,13,appliances.environment.air_conditioner,ava,2,182.83
...,...,...,...,...,...,...,...
92750,1515915625514887424,6,9,electronics.smartphone,samsung,1,208.31
92751,1515915625514887936,6,9,computers.notebook,asus,1,3472.20
92752,1515915625514888704,6,9,electronics.smartphone,oppo,3,752.49
92753,1515915625514891008,6,10,electronics.smartphone,apple,1,925.67
92754,1515915625514891264,6,10,electronics.smartphone,apple,1,418.96

In [271]:
user_p['age']=dt.age
user_p['sex']=dt.sex
user_p['local']=dt.local
user_p=pd.merge(user_p,rfm,how='inner',on='user_id')
user_p

,user_id,weekday,hour,category_code,brand,buy_cnt,amount,age,sex,local,最后消费日期,F,M,R
0,1515915625439951872,4,6,electronics.video.tv,lg,1,416.64,24.00,女,海南,2020-07-09,1,416.64,135
1,1515915625440038400,2,5,computers.network.router,asus,2,56.43,38.00,女,北京,2020-10-28,2,56.43,24
2,1515915625440051712,1,15,electronics.smartphone,apple,13,7489.53,32.00,女,广东,2020-11-16,2,7489.53,5
3,1515915625440099840,5,9,R,nordland,21,4929.86,20.00,男,重庆,2020-11-08,12,4929.86,13
4,1515915625440121600,2,13,appliances.environment.air_conditioner,ava,2,182.83,21.00,男,北京,2020-07-14,2,182.83,130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92750,1515915625514887424,6,9,electronics.smartphone,samsung,1,208.31,43.00,男,广东,2020-11-21,1,208.31,0
92751,1515915625514887936,6,9,computers.notebook,asus,1,3472.20,45.00,女,北京,2020-11-21,1,3472.20,0
92752,1515915625514888704,6,9,electronics.smartphone,oppo,3,752.49,45.00,女,北京,2020-11-21,1,752.49,0
92753,1515915625514891008,6,10,electronics.smartphone,apple,1,925.67,33.00,女,湖南,2020-11-21,1,925.67,0
92754,1515915625514891264,6,10,electronics.smartphone,apple,1,418.96,36.00,男,湖北,2020-11-21,1,418.96,0

In [272]:
user_p.F.describe()

count   92755.00
mean        2.51
std         4.56
min         1.00
25%         1.00
50%         1.00
75%         3.00
max       159.00
Name: F, dtype: float64

In [273]:
bins1=[0,3,10,20,200]
labels=['低频消费者','中频消费者','高频消费者','超高频狂热消费者']
user_p['消费频次']=pd.cut(user_p.F,bins=bins1,labels=labels)
user_p.head()

,user_id,weekday,hour,category_code,brand,buy_cnt,amount,age,sex,local,最后消费日期,F,M,R,消费频次
0,1515915625439951872,4,6,electronics.video.tv,lg,1,416.64,24.00,女,海南,2020-07-09,1,416.64,135,低频消费者
1,1515915625440038400,2,5,computers.network.router,asus,2,56.43,38.00,女,北京,2020-10-28,2,56.43,24,低频消费者
2,1515915625440051712,1,15,electronics.smartphone,apple,13,7489.53,32.00,女,广东,2020-11-16,2,7489.53,5,低频消费者
3,1515915625440099840,5,9,R,nordland,21,4929.86,20.00,男,重庆,2020-11-08,12,4929.86,13,高频消费者
4,1515915625440121600,2,13,appliances.environment.air_conditioner,ava,2,182.83,21.00,男,北京,2020-07-14,2,182.83,130,低频消费者

In [274]:
user_p.M.describe()

count    92755.00
mean      1239.68
std       4129.72
min          0.00
25%        148.11
50%        456.89
75%       1141.17
max     160604.07
Name: M, dtype: float64

In [275]:
bins2=[10,150,500,2500,200000]
labels2=['低消费用户','中消费用户','高消费用户','超高狂热消费用户']
user_p['消费金额']=pd.cut(user_p.M,bins=bins2,labels=labels2)
user_p.head()

,user_id,weekday,hour,category_code,brand,buy_cnt,amount,age,sex,local,最后消费日期,F,M,R,消费频次,消费金额
0,1515915625439951872,4,6,electronics.video.tv,lg,1,416.64,24.00,女,海南,2020-07-09,1,416.64,135,低频消费者,中消费用户
1,1515915625440038400,2,5,computers.network.router,asus,2,56.43,38.00,女,北京,2020-10-28,2,56.43,24,低频消费者,低消费用户
2,1515915625440051712,1,15,electronics.smartphone,apple,13,7489.53,32.00,女,广东,2020-11-16,2,7489.53,5,低频消费者,超高狂热消费用户
3,1515915625440099840,5,9,R,nordland,21,4929.86,20.00,男,重庆,2020-11-08,12,4929.86,13,高频消费者,超高狂热消费用户
4,1515915625440121600,2,13,appliances.environment.air_conditioner,ava,2,182.83,21.00,男,北京,2020-07-14,2,182.83,130,低频消费者,中消费用户

In [277]:
user_p['周消费喜好']=user_p['weekday'].apply(lambda x:'喜欢在周'+str(x)+'购物')
user_p['小时消费喜好']=user_p['hour'].apply(lambda x:'喜欢'+str(x)+'点购物')
user_p['喜欢购买类别']=user_p['category_code'].apply(lambda x:'购买过'+str(x))
user_p['品牌偏好']=user_p['brand'].apply(lambda x:'喜欢'+str(x)+'品牌')
user_p['年龄']=user_p['age'].apply(lambda x:str(x)+'岁')
user_p['最近购买时间']=user_p['R'].apply(lambda x:'最近消费在'+str(x)+'天前')

user_p.head()

In [278]:
user_p.head()

,user_id,weekday,hour,category_code,brand,buy_cnt,amount,age,sex,local,...,M,R,消费频次,消费金额,周消费喜好,小时消费喜好,喜欢购买类别,品牌偏好,年龄,最近购买时间
0,1515915625439951872,4,6,electronics.video.tv,lg,1,416.64,24.00,女,海南,...,416.64,135,低频消费者,中消费用户,喜欢在周4购物,喜欢6点购物,购买过electronics.video.tv,喜欢lg品牌,24.0岁,最近消费在135天前
1,1515915625440038400,2,5,computers.network.router,asus,2,56.43,38.00,女,北京,...,56.43,24,低频消费者,低消费用户,喜欢在周2购物,喜欢5点购物,购买过computers.network.router,喜欢asus品牌,38.0岁,最近消费在24天前
2,1515915625440051712,1,15,electronics.smartphone,apple,13,7489.53,32.00,女,广东,...,7489.53,5,低频消费者,超高狂热消费用户,喜欢在周1购物,喜欢15点购物,购买过electronics.smartphone,喜欢apple品牌,32.0岁,最近消费在5天前
3,1515915625440099840,5,9,R,nordland,21,4929.86,20.00,男,重庆,...,4929.86,13,高频消费者,超高狂热消费用户,喜欢在周5购物,喜欢9点购物,购买过R,喜欢nordland品牌,20.0岁,最近消费在13天前
4,1515915625440121600,2,13,appliances.environment.air_conditioner,ava,2,182.83,21.00,男,北京,...,182.83,130,低频消费者,中消费用户,喜欢在周2购物,喜欢13点购物,购买过appliances.environment.air_conditioner,喜欢ava品牌,21.0岁,最近消费在130天前

In [279]:
text=user_p.iloc[50335].tolist()[14:]
text

['低频消费者',
 '高消费用户',
 '喜欢在周3购物',
 '喜欢10点购物',
 '购买过R',
 '喜欢samsung品牌',
 '20.0岁',
 '最近消费在141天前']

In [280]:
dic=dict(zip(text,[15,80,60,100,250,180,56,5]))
dic

{'低频消费者': 15,
 '高消费用户': 80,
 '喜欢在周3购物': 60,
 '喜欢10点购物': 100,
 '购买过R': 250,
 '喜欢samsung品牌': 180,
 '20.0岁': 56,
 '最近消费在141天前': 5}

In [281]:
from pyecharts.charts import WordCloud

In [283]:
p_user_p=(WordCloud()
         .add('',[z for z in dic.items()],word_size_range=[12,55])
         .set_global_opts(title_opts=opts.TitleOpts(title='用户画像')))
p_user_p.render_notebook()